### ISSUE TITLE
bug: Cannot import getVariable, setVariable in inline typescript scripts

### ISSUE THREAD

**Issue by abulka** [windmill-labs/windmill#1613]
### Describe the bug

When I import  { getVariable, setVariable } as per the [documentation](https://docs.windmill.dev/docs/core_concepts/variables_and_secrets#user-defined-variables) I get the error running the script
```
ExecutionErr: ExitCode: 1, last log lines: error: Uncaught SyntaxError: The requested module 'https://deno.land/x/windmill@v1.101.1/mod.ts' does not provide an export named 'setVariable' import { getVariable, setVariable } from "https://deno.land/x/windmill@v1.101.1/mod.ts"; ^ at <anonymous> (file:///tmp/windmill/dt-worker-BtaqF-hr1jP/01883dcf-ce19-aa8d-44fb-afa44d3c874f/main.ts:3:23) 
```

### To reproduce

1. Create a button in an app in a workspace in the cloud https://app.windmill.dev/ 
2. add a typescript inline script
```typescript
import { getVariable, setVariable } from "https://deno.land/x/windmill@v1.101.1/mod.ts";

export async function main(x: string) {
  let foo = getVariable("u/andy/foo");
  foo++;
  setVariable("u/andy/foo", foo);
  return foo;
}
```

4. Define the variable 'u/andy/foo' 
5. Run the script
6. See error

### Expected behavior

I should get access to  { getVariable, setVariable } and be able to use them.

The Python inline script doing the same thing, as per the official example, works ok.

Importing `import * as wmill from "https://deno.land/x/windmill@v1.102.0/mod.ts"` causes a similar import problem.

### Browser information

Chrome Version 113.0.5672.126 (Official Build) (x86_64)

### Application version

cannot locate this - am using cloud version on 21st May 2023

**Comment by rubenfiszel** [comment]
Fixed in commit: 501bb11d , will do a release this hour.

**Comment by rubenfiszel** [comment]
Released in 1.102.1

**Comment by abulka** [comment]
Just download latest docker image today, still getting
```
Uncaught SyntaxError: The requested module 'https://deno.land/x/windmill@v1.101.1/mod.ts' does not provide an export named 'setVariable' setVariable
```

Where can I find the version of Windmill that I am running using the UI? Perhaps the fix hasn't perculated yet?

docker says:
```
~$ docker images
REPOSITORY                                                                                      TAG            IMAGE ID       CREATED        SIZE
ghcr.io/windmill-labs/windmill                                                                  main           4ec0a9bd35e3   12 hours ago   1.32GB
ghcr.io/windmill-labs/windmill-lsp                                                              latest         2fd1c21d27d9   24 hours ago   2.38GB
```

**Comment by rubenfiszel** [comment]
You need to bump the library version (in the import)
