### ISSUE TITLE
What are the actual rules for concurrency limits?

### ISSUE THREAD

**Issue by yureckey** [windmill-labs/windmill#1924]
### Describe the bug

I don't know if it's worked that way before, but I don't think current cloud version works properly for concurrency. Or I just don't get it.
Exhibit 1:
primitive script (return static string), set concurrency 1 for window 60 seconds - doesn't work at all, reschedule every minute for next minute.
Exhibit 2:
same script, set concurrency 2 for window 120 seconds - works, but execution queue is not what I expected.

I launched 5 async webhooks for this script, one by one with about second delay between calls.
I would expect first two executes immediately, then pause for about two minutes and another two executions, then two minutes pause and last one executed.
In actual test script 1 executed immediately, then 2 minutes pause, script 2,3 executed, then 2 minutes pause script 4 executed, then 2 minutes pause script 5 executed. Is that how it supposed to work?

here is filtered logs of jobruns

82da8536
Received job: 08:27 PM 22/7
Started: 08:27 PM 22/7
job 01897dff-24cf-af04-a56f-2d1382da8536 on worker wk-xk84s-lCzUu

2952288e
Received job: 08:27 PM 22/7
Started: 08:29 PM 22/7
Re-scheduled job to 2023-07-22 14:29:00.455394 UTC due to concurrency limits
job 01897dff-2afc-847e-73c2-2d302952288e on worker wk-g66g9-gUNKn

e3c335ae
Received job: 08:27 PM 22/7
Started: 08:29 PM 22/7
Re-scheduled job to 2023-07-22 14:29:00.455394 UTC due to concurrency limits
job 01897dff-3018-6cbe-2980-b252e3c335ae on worker wk-vzz6h-tjkIe

cedeb9e9
Received job: 08:27 PM 22/7
Started: 08:31 PM 22/7
Re-scheduled job to 2023-07-22 14:29:00.455394 UTC due to concurrency limits
Re-scheduled job to 2023-07-22 14:31:02.474358 UTC due to concurrency limits
job 01897dff-3a0f-616d-a492-4ddfcedeb9e9 on worker wk-2jcgl-advbJ

8aa3e01f
Received job: 08:27 PM 22/7
Started: 08:33 PM 22/7
Re-scheduled job to 2023-07-22 14:29:00.455394 UTC due to concurrency limits
Re-scheduled job to 2023-07-22 14:31:02.474358 UTC due to concurrency limits
Re-scheduled job to 2023-07-22 14:33:03.493653 UTC due to concurrency limits
job 01897dff-433b-821f-0c1c-47808aa3e01f on worker wk-vzz6h-tjkIe

### To reproduce

any simple script. set concurrency 1 _ 60. Then 2 _ 120

### Expected behavior

well, for concurrency 1 - working run. For concurrency > 1 - it's not clear what is the proper queue algorithm here

### Application version

Windmill EE v1.134.2

**Comment by rubenfiszel** [comment]
Thanks for the report, I think we had an off by one error that I just fixed: https://github.com/windmill-labs/windmill/commit/a054bdd0438567996b551b1b00a4c0697ce61986

We did some changes to do the check inside a transaction and it changed a bit the behavior which is why we didn't catch it.

**Comment by yureckey** [comment]
Thanks, I tested on current cloud 1.34.2 and it's more predictable. But I still don't quite get it. I was expecting FIFO queue, but in my tests the order of execution wasn't linear FIFO. Concurrency rule 2_60s, I send 10 requests one by one with 2 seconds delay. Here is a list of jobs in the order I sent it, and next to id is the number when it actually was executed (with log for reschedules):

01898352-03e1-bbce-ba31-095d25a543b8  1
job 01898352-03e1-bbce-ba31-095d25a543b8 on worker wk-bdrsf-O61Yy

01898352-0d2f-2a56-aebb-53f741aac35e  2
job 01898352-0d2f-2a56-aebb-53f741aac35e on worker wk-2pmmc-a1zlI

01898352-168b-cc9a-6dd2-0fc211411c3c  batch of 7-8-9
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:17:38.615343 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:18:41.625242 UTC due to concurrency limits
job 01898352-168b-cc9a-6dd2-0fc211411c3c on worker wk-2t8mh-ZKjqU

01898352-1f67-06b7-f7c7-4cad36ad2dd3  batch of 3-4
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
job 01898352-1f67-06b7-f7c7-4cad36ad2dd3 on worker wk-qhlkc-FnE4X

01898352-28d8-8465-b4fb-c15390402a3e  batch of 7-8-9
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:17:38.615343 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:18:41.625242 UTC due to concurrency limits
job 01898352-28d8-8465-b4fb-c15390402a3e on worker wk-bdrsf-O61Yy

01898352-3215-2b0f-584a-270b2713a88e  10
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:17:38.615343 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:18:41.625242 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:19:44.634574 UTC due to concurrency limits
job 01898352-3215-2b0f-584a-270b2713a88e on worker wk-lz7lr-89ES7

01898352-3b71-5b8c-1211-2fbd56f9104c  batch of 3-4
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
job 01898352-3b71-5b8c-1211-2fbd56f9104c on worker wk-2t8mh-ZKjqU

01898352-44d0-74d6-1c57-bed98070177c  batch of 5-6
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:17:38.615343 UTC due to concurrency limits
job 01898352-44d0-74d6-1c57-bed98070177c on worker wk-phq56-VBMu4

01898352-4e28-9760-7d27-8cb372075810  batch of 7-8-9
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:17:38.615343 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:18:41.625242 UTC due to concurrency limits
job 01898352-4e28-9760-7d27-8cb372075810 on worker wk-qhlkc-FnE4X

01898352-577c-dbe9-1120-5be63996f4f9  batch of 5-6
Re-scheduled job to 2023-07-23 15:16:37.585499 UTC due to concurrency limits
Re-scheduled job to 2023-07-23 15:17:38.615343 UTC due to concurrency limits
job 01898352-577c-dbe9-1120-5be63996f4f9 on worker wk-2t8mh-ZKjqU

so, order looks a bit chaotic

**Comment by rubenfiszel** [comment]
@yureckey This should be now solved since we now use 'created_at' as second order sort and that should ensure FIFO ordering.

**Comment by rubenfiszel** [comment]
@yureckey were you able to confirm it now work as expected?

**Comment by yureckey** [comment]
Well, I'm on cloud EE v1.137.1-22-gada9b9f0 I did a quick test with 10 of same postman request to same test script. And then I watched executions in the "runs" list - it was almost linear, although a couple of requests were not in order. I didn't checked thoroughly by id, maybe runs list wasn't ordered properly by itself
