### ISSUE TITLE
bug: enable response headers with cache-control on JS and CSS files

### ISSUE THREAD

**Issue by ebertti** [windmill-labs/windmill#4547]
### Describe the bug

Just a configuration of the server, today all the static files from the application has no-cache response.

I'm running self hosted with raspberry pi 5 for testing, and it took like a minute to start the application.

### To reproduce

response header from a chunk of JS file:

`Cache-Control: no-cache, no-store, must-revalidate`

### Expected behavior

something like 

`cache-control: max-age=31536000`

### Screenshots

![image](https://github.com/user-attachments/assets/a6995a9e-37d0-4067-ad74-bf697cdf5e5e)

**Comment by rubenfiszel** [comment]
fixed on latest, we were caching application/javascript but not text/javascript -_-

Thanks for the report!

**Comment by ebertti** [comment]
I update docker tag to: 1.410.3 and still getting no-cache on cache-control header.

![image](https://github.com/user-attachments/assets/2bccd511-e776-45c0-b354-168e1a67bb4e)
